// Mock API service to simulate backend endpoints
// This is useful for testing when the actual API is not available

// Mock data storage
let mockChatHistory = [
  {
    id: "1",
    question: "What is photosynthesis?",
    answer: "Photosynthesis is the process by which green plants prepare food.",
    citation: "NCERT Class 9 Chapter 5",
    lang: "en"
  },
  {
    id: "2",
    question: "Explain Newton's laws of motion",
    answer: "Newton's laws of motion describe the relationship between a body and the forces acting upon it.",
    citation: "NCERT Class 11 Chapter 4",
    lang: "en"
  }
];

// Generate a random ID
const generateId = () => Math.random().toString(36).substr(2, 9);

// Mock delay to simulate network request
const mockDelay = (ms = 1000) => new Promise(resolve => setTimeout(resolve, ms));

// Mock API functions
export const mockApiService = {
  // GET /chat/history - Fetch previous Q&A history
  getChatHistory: async () => {
    console.log('Mock API: Fetching chat history');
    await mockDelay();
    return { data: mockChatHistory, status: 200 };
  },

  // POST /chat/ask - Send user's question and get the answer
  askQuestion: async (questionData) => {
    console.log('Mock API: Asking question', questionData);
    await mockDelay();
    
    // Simple logic to generate mock answers based on the question
    let answer = "This is a sample answer to your question. In a real application, this would be generated by an AI model.";
    let citation = "NCERT Reference Material";
    
    if (questionData.question.toLowerCase().includes('photosynthesis')) {
      answer = "Photosynthesis is the process by which green plants convert sunlight into chemical energy. During photosynthesis, plants use carbon dioxide from the air and water from the soil to produce glucose and oxygen. This process takes place in the chloroplasts of plant cells, specifically using chlorophyll to capture light energy.";
      citation = "NCERT Class 9 Science Chapter 5 - Fundamental Unit of Life";
    } else if (questionData.question.toLowerCase().includes('gravity')) {
      answer = "Gravity is a natural phenomenon by which all things with mass or energy are brought toward one another. On Earth, gravity gives weight to physical objects and causes the ocean tides. Gravity has an infinite range, although its effects become weaker as objects get farther apart.";
      citation = "NCERT Class 11 Physics Chapter 8 - Gravitation";
    } else if (questionData.question.toLowerCase().includes('democracy')) {
      answer = "Democracy is a form of government in which the people have the authority to choose their governing legislation. Who people are and how authority is shared among them are fundamental questions for democratic theory. The core of democracy is equality in voting, discussion, criticism, personal autonomy, and human rights to free speech and association.";
      citation = "NCERT Class 9 Political Science Chapter 1 - Democracy in the Contemporary World";
    }
    
    const newEntry = {
      id: generateId(),
      question: questionData.question,
      answer: answer,
      citation: citation,
      lang: questionData.lang || "en"
    };
    
    // Add to mock history
    mockChatHistory.unshift(newEntry);
    
    return { data: newEntry, status: 200 };
  },

  // POST /chat/feedback - Record feedback for that Q&A
  submitFeedback: async (feedbackData) => {
    console.log('Mock API: Submitting feedback', feedbackData);
    await mockDelay();
    
    // In a real application, this would store the feedback in a database
    return { 
      data: { 
        message: "Feedback recorded successfully", 
        feedback: feedbackData 
      }, 
      status: 200 
    };
  },

  // GET /chat/citation/:id - Get NCERT reference for that answer
  getCitation: async (id) => {
    console.log('Mock API: Getting citation for ID', id);
    await mockDelay();
    
    const entry = mockChatHistory.find(item => item.id === id);
    
    if (entry) {
      return { 
        data: { 
          id: entry.id,
          citation: entry.citation,
          fullReference: `Detailed reference information for: ${entry.citation}`
        }, 
        status: 200 
      };
    } else {
      return { 
        data: { 
          error: "Citation not found" 
        }, 
        status: 404 
      };
    }
  }
};

export default mockApiService;